baseURL = "https://eric-walters.ca/"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Eric Walters"
    languageName = "English"
    weight = 1
  [languages.fr]
    title = "Eric Walters"
    languageName = "Fran√ßais"
    weight = 2
  [languages.de]
    title = "Eric Walters"
    languageName = "Deutsch"
    weight = 3

theme = "blowfish"
