[[main]]
  name = "Ãœber mich"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Erfahrung"
  pageRef = "experience"
  weight = 2

[[main]]
  name = "Projekte"
  pageRef = "projects"
  weight = 3

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 4

[[main]]
  name = "Lebenslauf"
  pageRef = "cv"
  weight = 5

[[main]]
  name = "Kontakt"
  pageRef = "contact"
  weight = 6
