[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Experience"
  pageRef = "experience"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 40

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 50

[[main]]
  name = "Download CV"
  url = "/resume.pdf"
  weight = 60
  [main.params]
    target = "_blank"
