[[main]]
  name = "Ãœber mich"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Erfahrung"
  pageRef = "experience"
  weight = 20

[[main]]
  name = "Projekte"
  pageRef = "projects"
  weight = 30

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 40

[[main]]
  name = "Kontakt"
  pageRef = "contact"
  weight = 50

[[main]]
  name = "Lebenslauf"
  url = "/resume.pdf"
  weight = 60
  [main.params]
    target = "_blank"
