[[main]]
  name = "À propos"
  pageRef = "about"
  weight = 1

[[main]]
  name = "Expérience"
  pageRef = "experience"
  weight = 2

[[main]]
  name = "Projets"
  pageRef = "projects"
  weight = 3

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 4

[[main]]
  name = "CV"
  pageRef = "cv"
  weight = 5

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 6
