[[main]]
  name = "About"
  url = "/about"
  weight = 1

[[main]]
  name = "Experience"
  url = "/experience"
  weight = 2

[[main]]
  name = "Projects"
  url = "/projects"
  weight = 3

[[main]]
  name = "Blog"
  url = "/blog"
  weight = 4

[[main]]
  name = "CV"
  url = "/cv"
  weight = 5

[[main]]
  name = "Contact"
  url = "/contact"
  weight = 6
