colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = true
enableSearch = true
homepage.layout = "profile"
homepage.showRecent = true

[author]
  name = "Eric Walters"
  headline = "Mechanical Engineering, B.Sc. · University of Alberta · 2026"

[author.links]
  github = "eric-walters"
  linkedin = "eric-g-w"
  email = "contact@eric-walters.ca"
